### ISSUE TITLE
How to setup?

### ISSUE THREAD

**Issue by Joly0** [ozangulle/plauna#5]
Hey, i am currently trying to figure out how to actually run this. I have started plauna without a config or edn file as per the docs this option will be deprecated soon. After startup i am faced with this:

<img width="1795" height="378" alt="Image" src="https://github.com/user-attachments/assets/21d5ee84-11f0-4cab-89f9-e8706ad5dbbf" />
but there is actually nothing to do other than to upload a file. 

https://github.com/ozangulle/plauna?tab=readme-ov-file#getting-started mentions to configure a watcher, but there is no option for this anywhere. I thought i could configure an imap connection, but when i click that on the webui, i only see this:

<img width="1795" height="247" alt="Image" src="https://github.com/user-attachments/assets/d65a9708-b34b-4540-9f13-c2ba577d79be" />

I understand this is heavy in development, would still be nice though to have some docs that one could follow to set this up. I am not sure what i can do now or am supposed to do

**Comment by ozangulle** [comment]
Hi @Joly0. I implemented oauth2 authentication for IMAP connections. The changes are currently in the "oauth" branch. I haven't merged them with master yet because I could only test it with Gmail. I guess I am not important enough for Microsoft to access their development program.
Anyway I have been testing the branch on my server and it's running stable. Would you be so kind to test it with an Outlook account? You can find the documentation for oauth [here](https://github.com/ozangulle/plauna/tree/oauth?tab=readme-ov-file#authentication)

**Comment by Joly0** [comment]
Hey @ozangulle  so i see you have made some changes and so far i dont get this error anymore. I was hitting some problems with the "scope" field, but i guess i have found the correct settings, but i still get an error when authenticating:
`2025-12-11T02:57:10.575604466Z ERROR LOG 2f2c0386efa6 plauna.client[364,49] jakarta.mail.AuthenticationFailedException: AUTHENTICATE failed.`

This is after configuring everything, saving and then pressing the "connect" button. I get redirected to the microsoft login page, can normally login and connect with the app i created in entra id and then when i get redirected back to plauna i see, that i am not logged in and in the logs of the docker contaienr i get the error above

The scope i have configured at the moment is:
`User.Read offline_access IMAP.AccessAsUser.All`

**Comment by Joly0** [comment]
Also the problem is, i cannot see, what the access and refresh tokens are, that plauna receives from microsoft entra, so i cannot check if they are even valid at all and what scopes they cover. I cannot even see them in debug mode.

**Comment by ozangulle** [comment]
The reason you were redirected the first time was to get an access and a refresh token. Plauna stores the refresh token in the db so when you click connect again, it just gets a new access token using the refresh token. This is why you are not redirected to the MS login page again.

Plauna's db is in the data folder you specified when you started it. It's a sqlite database called "email.db". You can open it using sqlite3 email.db and get all the token info stored in it from the table "oauth_tokens". I think it's a security feature of the email library that I'm using (jakarta mail for java) that it doesn't show you the login details in the logs.
